### ISSUE TITLE
module is not working.

### ISSUE THREAD

**Issue by sivajik34** [archonkulis/ANSolutions_CssJsTimestamp#1]
this is not working as expected.Can you look into this ?
timestamp not updating.

**Comment by archonkulis** [comment]
@sivajik34 Hey! Have you tried clearing Magento cache afterwards? As mentioned in description:

`To force timestamp change, go to System -> Cache Management -> click on "Flush Browser Cached CSS/JS" and then "Flush Cache Storage"`

You could also try first clearing Magento cache before Flush Cache Storage.

Please check and let me know if helped.

Cheers

PS - the link you provided isn't working for me.

**Comment by sivajik34** [comment]
Now link is working.can you check please. i did what you said.
but i have to refresh  with ctrl f5

**Comment by sivajik34** [comment]
above file is not updating .
skin/frontend/tm_themes/theme349k/css/custom.css
i'm trying to modify color -product name
.product-view .product-img-box .product-name h1, .product-view .product-img-box .product-name h2, .product-view .product-shop .product-name .h1 {
      font-size: 20px;
      color: yellow !important;
  }

**Comment by archonkulis** [comment]
@sivajik34 

Can you please check if the module is enabled and there are no other rewrites to the Mage_Page_Block_Html_Head class?

I haven't tested it with css/js merge enabled, though. Will check tomorrow, but I don't think there should be any problems.

Will let you know tomorrow how it goes, but meanwhile please check what I asked for. You could also try clearing css/js ( https://prnt.sc/jqn3k2 )

Cheers

**Comment by sivajik34** [comment]
@archonkulis head block is overridden by  3rd party mirasvit seo module.sorry for the inconvenience.
